### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yNicollas** [TitaniumMC/Titanium#130] opened 2023-01-09 12:45 UTC
Error while using WorldGuard in java 8

https://hastebin.com/bumapomiga.properties

**Comment by c0dingnoobi** [comment] 2023-01-09 12:46
#126

**Comment by P3ridot** [comment] 2023-01-09 12:46
Duplicate of #79 

And use WorldGuars 6.2.1 (that for 1.12.2)

**Closed by P3ridot** 2023-01-09 12:46 UTC
Labels: duplicate, plugin compatibility
