### ISSUE TITLE
1.7 DecoderException kick (UnpooledHeapByteBuf)

### ISSUE THREAD

**Issue by c0dingnoobi** [TitaniumMC/Titanium#109] opened 2022-11-13 20:43 UTC
It is hard to explain how to reproduce this behaviour. Basically just have Viaversion and Viarewind installed. 
It can happen on death events on world change events, when players join server/world. 

![image](https://user-images.githubusercontent.com/97745777/201543502-40a97b31-88e8-496f-bce0-1435f5152898.png)

Doesn't happen on Panda and vanilla. My guess is that it is caused by a patch One, which is in WindSpigot's patch list and in Titanium's patch list (since this behaviour is also reproduceable using WindSpigot)

**Comment by c0dingnoobi** [comment] 2022-11-15 18:43
Seems like you have less time these days. So I have made a list containing all patches which are present in titanium and wind (since the cause must be one of those). 
https://pastebin.com/VfKeeLcn

**Comment by P3ridot** [comment] 2022-11-15 20:44
I have 1 question... Are you using async entity tracker or async hit detection/knockback?

**Comment by c0dingnoobi** [comment] 2022-11-15 20:51
No both are disabled.

**Comment by P3ridot** [comment] 2022-11-15 21:00
Okay, could test it on completely clean server (don't use your current server environment because it could courrput - just install titanium and ViaVersion and ViaRewind) - but also using this old realase https://github.com/TitaniumMC/Titanium/releases/tag/0.4.0 ? There we only had PandaSpigot patches without any WindSpigot... If problem is also there it's probably wrongly implemented PandaSpigot patches

**Comment by c0dingnoobi** [comment] 2022-11-15 21:04
I can test it yes, no problem at all. But as said i highly doubt that it has something to do with panda. I don't think that panda made a patch against this behaviour instead i do think that the reason is caused by a patch which is in titanium but not in panda.
But regardless, yea i can test it and see if it still happens

**Comment by c0dingnoobi** [comment] 2022-11-15 22:38
Doesn't happen on https://github.com/TitaniumMC/Titanium/releases/tag/0.4.0, just tried for nearly whole hour to confirm. 
Then switched back to newest and it happened after testing 5mins. 
Ran clean localhosted without proxy with only viaversion and viarewind.

**Comment by P3ridot** [comment] 2022-11-16 08:47
Okay, so yeah maybe it's caused by some WindSpigot patch. 

And to test that I only have to start server with ViaRewind?

**Comment by c0dingnoobi** [comment] 2022-11-16 10:33
You would somehow need to make the player perform many tasks at once. Like teleporthin while he is dying. Or still pressing multitple keys before death. It is kind of hard to explain. I have found a way some day ago to force it to happen by using a 1v1 plugin which teleports the player on death back to main world.

**Comment by P3ridot** [comment] 2022-11-27 10:28
Fixed in `dev` branch

**Closed by P3ridot** 2022-11-27 10:28 UTC
Labels: bug

**Comment by ItsClairton** [comment] 2022-12-19 23:08
I am also having the same problem (version dev-105), but it also happens with PandaSpigot, however not with Paper and not with the default spigot.

![image](https://user-images.githubusercontent.com/28469592/208545327-e4666d47-b321-4f7f-ab88-0e020b2eb834.png)

**Comment by c0dingnoobi** [comment] 2022-12-19 23:10
Thats weird, it didnt happen for me with panda neither it does happen since the cleanup-branch (#112 )
You got any steps to reproduce?

**Comment by ItsClairton** [comment] 2022-12-19 23:32
Basically, walking around, sometimes you get kicked out, but it's very random.

**Comment by c0dingnoobi** [comment] 2022-12-19 23:49
Which plugins you have, also is this reproduceable on any 1.7 client (likar lunar, vanilla, badlion etc)

**Comment by ItsClairton** [comment] 2022-12-20 00:13
Many, most are proprietary, with the exception of Citzens, HolographicDisplays, LuckPerms, PlayerParticles, PlugMan, ProtocolLib, ShopKeepers, ServerSigns, Vault, WorldEdit, WorldGuard, and spark.

And yes, it happens with vanilla too.

**Comment by c0dingnoobi** [comment] 2022-12-20 00:18
Since when does this issue keep happening for you.
Did it work before? Have you recently updated any plugins. 
I guess it doesn't have to do with titaniums latest changes since you mentioned it already happened on Panda. 
The AsyncEntityTracker (which was the cause for my issue) is out of options since Panda does not have it.
